# Generated by Django 5.2.17 on 2026-09-09 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=60)),
                ('grade', models.CharField(blank=True, max_length=60)),
                ('model_name', models.CharField(max_length=80)),
                ('model_code', models.CharField(blank=True, max_length=40)),
                ('chassis_number', models.CharField(max_length=40, unique=True)),
                ('manufacture_year', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('lpg', 'LPG')], default='petrol', max_length=10)),
                ('seat_capacity', models.PositiveSmallIntegerField(default=5)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('price_jpy', models.PositiveIntegerField(blank=True, help_text="Leave blank to display 'Call for price' instead of an amount.", null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=10)),
                ('description_en', models.TextField(blank=True)),
                ('description_ja', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('is_primary', models.BooleanField(default=False, help_text='Shown on the listing card. Only the first one counts.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
