# Generated by Django 5.2.17 on 2026-09-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='video',
            field=models.FileField(blank=True, help_text='Optional MP4 walkaround. Nothing downloads until a visitor presses play.', upload_to='cars/video/'),
        ),
        migrations.AddField(
            model_name='car',
            name='video_uploaded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='carimage',
            name='derivative_widths',
            field=models.CharField(blank=True, editable=False, help_text='Widths actually generated. Narrower than DERIVATIVE_WIDTHS when the original was too small to produce them all.', max_length=64),
        ),
        migrations.AddField(
            model_name='carimage',
            name='derivatives_ready',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
