# Generated by Django 5.2.17 on 2026-09-10 01:18

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cars', '0002_car_video_car_video_uploaded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
            ],
            options={
                'verbose_name': 'staff account',
                'verbose_name_plural': 'staff accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
