# Generated by Django 5.2.17 on 2026-09-10 04:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestDriveSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(help_text='Local time in Japan, e.g. 18:30.')),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveSmallIntegerField(default=1, help_text='How many customers can take this appointment at once - two cars or two staff free means 2.', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('starts_on', models.DateField(blank=True, help_text='Optional. Leave blank to start immediately.', null=True)),
                ('ends_on', models.DateField(blank=True, help_text='Optional. Leave blank to run indefinitely.', null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('weekday', 'start_time', 'end_time'), name='unique_test_drive_rule')],
            },
        ),
        migrations.CreateModel(
            name='TestDriveSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_open', models.BooleanField(default=True, help_text='Untick to close this one appointment. Regenerating slots leaves your choice alone.')),
                ('schedule', models.ForeignKey(blank=True, help_text='The rule this came from. Cleared if the rule is deleted, so slots people already booked survive.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='cars.testdriveschedule')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='TestDriveBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_label', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'Did not attend')], default='booked', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_drive_bookings', to='cars.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drive_bookings', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cars.testdriveslot')),
            ],
            options={
                'ordering': ['slot__starts_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='testdriveslot',
            constraint=models.UniqueConstraint(fields=('schedule', 'starts_at'), name='unique_slot_per_rule_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='testdrivebooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('slot', 'customer'), name='one_live_booking_per_customer_per_slot'),
        ),
    ]
