# Generated by Django 5.2.17 on 2026-09-10 05:10

from django.conf import settings
from django.db import migrations, models


def map_booked_to_confirmed(apps, schema_editor):
    """Any row written before staff approval existed was already accepted."""
    apps.get_model("cars", "TestDriveBooking").objects.filter(status="booked").update(
        status="confirmed"
    )


def map_confirmed_to_booked(apps, schema_editor):
    apps.get_model("cars", "TestDriveBooking").objects.filter(
        status__in=["confirmed", "pending"]
    ).update(status="booked")


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_test_drive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testdrivebooking',
            name='one_live_booking_per_customer_per_slot',
        ),
        migrations.AddField(
            model_name='testdrivebooking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testdrivebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'Did not attend')], default='pending', max_length=12),
        ),
        migrations.RunPython(map_booked_to_confirmed, map_confirmed_to_booked),
        migrations.AddConstraint(
            model_name='testdrivebooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('slot', 'customer'), name='one_live_booking_per_customer_per_slot'),
        ),
    ]
