# Generated by Django 5.2.17 on 2026-09-10 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_pending_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Editable before publishing. People type phone numbers and names into free text, and this goes on a public page.')),
                ('answer', models.TextField(blank=True, default='')),
                ('answered_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_published', models.BooleanField(default=False, help_text="Shows the question and your answer on the car's public page and in search results. The customer's name is never shown.")),
                ('language', models.CharField(choices=[('en', 'English'), ('ja', '日本語')], default='en', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_car_questions', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cars.car')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['car', 'is_published', '-created_at'], name='carq_public_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_published', False), models.Q(('answer', ''), _negated=True), _connector='OR'), name='published_question_has_an_answer')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('booking_confirmed', 'Test drive confirmed'), ('booking_cancelled', 'Test drive cancelled'), ('question_answered', 'Question answered')], max_length=32)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, default='', max_length=80)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='notif_feed_idx'), models.Index(condition=models.Q(('read_at__isnull', True)), fields=['customer'], name='notif_unread_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('customer', 'dedupe_key'), name='one_notification_per_event')],
            },
        ),
    ]
